# Default values for hello-icp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: mycluster.icp:8500/tools/hello-icp
  tag: 1.0.1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80