{
  "apiVersion": "v1",
  "kind": "Service",
  "metadata": {
    "name": "hello-icp-2",
    "namespace": "cert-manager",
    "labels": {
      "app": "hello-icp-2"
    }
  },
  "spec": {
    "ports": [
      {
        "name": "teste",
        "protocol": "TCP",
        "port": 9080,
        "targetPort": 9080,
        "nodePort": 30415
      }
    ],
    "selector": {
      "app": "hello-icp-2"
    },
    "clusterIP": "10.0.72.107",
    "type": "NodePort",
  }
}